# Generated by Django 3.1.6 on 2021-02-18 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='applicant_id',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='app.applicant', verbose_name='Applicant Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='area',
            field=models.CharField(default='', max_length=50, verbose_name='Area'),
        ),
        migrations.AddField(
            model_name='application',
            name='building_no',
            field=models.IntegerField(default=0, verbose_name='Building No'),
        ),
        migrations.AddField(
            model_name='application',
            name='contact1',
            field=models.CharField(default='', max_length=50, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='application',
            name='contact2',
            field=models.CharField(default='', max_length=50, verbose_name='Fax'),
        ),
        migrations.AddField(
            model_name='application',
            name='cr',
            field=models.CharField(default='', max_length=50, verbose_name='CR No'),
        ),
        migrations.AddField(
            model_name='application',
            name='cr_reg_date',
            field=models.DateField(blank=True, null=True, verbose_name='Registration Date'),
        ),
        migrations.AddField(
            model_name='application',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='application',
            name='flat_no',
            field=models.IntegerField(default=0, verbose_name='Flat No'),
        ),
        migrations.AddField(
            model_name='application',
            name='full_ar_name',
            field=models.CharField(default='', max_length=250, verbose_name='Commercial Arb Name'),
        ),
        migrations.AddField(
            model_name='application',
            name='full_en_name',
            field=models.CharField(default='', max_length=250, verbose_name='Commercial Eng Name'),
        ),
        migrations.AddField(
            model_name='application',
            name='intial_approval',
            field=models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject')], default='', max_length=50, verbose_name='Manager Decision'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='license_expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='License Expiry Date'),
        ),
        migrations.AddField(
            model_name='application',
            name='license_no',
            field=models.CharField(default='', max_length=50, verbose_name='License No'),
        ),
        migrations.AddField(
            model_name='application',
            name='manager_comments',
            field=models.TextField(default='', verbose_name='Manager Comments'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='road_no',
            field=models.IntegerField(default=0, verbose_name='Road No'),
        ),
        migrations.AddField(
            model_name='application',
            name='staff_comments',
            field=models.TextField(default='', verbose_name='Comments'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='app_type',
            field=models.CharField(choices=[('intial', 'Intial Approval'), ('new', 'New'), ('renewal', 'Renewal'), ('modify', 'Modify'), ('license_cancel', 'License Cancellation')], max_length=50, verbose_name='Application Type'),
        ),
        migrations.AlterField(
            model_name='application',
            name='financial_guarantee_expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Financial Guarantee Expiry Date'),
        ),
        migrations.AlterField(
            model_name='application',
            name='org_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.organization', verbose_name='Organization Name'),
        ),
        migrations.AlterField(
            model_name='application',
            name='user_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='organization',
            name='applicant_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.applicant', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='organization',
            name='user_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=''),
        ),
    ]
