# Generated by Django 3.1.6 on 2021-02-15 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_application_app_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='user_id',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name=''),
            preserve_default=False,
        ),
    ]
