# Generated by Django 3.1.6 on 2021-02-18 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_application_org_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applicant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.applicant', verbose_name='Applicant Name'),
        ),
        migrations.AlterField(
            model_name='application',
            name='cr',
            field=models.CharField(blank=True, max_length=50, verbose_name='CR No'),
        ),
    ]
