# Generated by Django 3.1.6 on 2021-02-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_organization_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='app_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('verification', 'Violations Verification'), ('request_statement', 'Request Statements'), ('review_statement', 'Reviewing Statements'), ('initial_approval', 'Inital Approval'), ('verify_documents', 'Verify Documents'), ('issue_decision', 'Issue the Decision'), ('paying_fees', 'Paying Fees'), ('paying_renewal_fees', 'Paying Renewal Fees'), ('paying_cancellation_fees', 'Paying Cancellation Fees'), ('done', 'Receive License'), ('cancellarion_done', 'Cancel License')], default='draft', max_length=50, verbose_name='Status'),
        ),
    ]
