# Generated by Django 3.1.6 on 2021-02-16 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_auto_20210216_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='emp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Employee Name'),
        ),
        migrations.AlterField(
            model_name='application',
            name='employment_office_receipt',
            field=models.FileField(upload_to='media\\doc_library', verbose_name='Employment Office Receipt'),
        ),
        migrations.AlterField(
            model_name='application',
            name='org_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.organization', verbose_name='Organization Name'),
        ),
        migrations.AlterField(
            model_name='application',
            name='rent_doc',
            field=models.FileField(upload_to='media\\doc_library', verbose_name='Rental Agreement Doc'),
        ),
    ]
