# Generated by Django 3.1.6 on 2021-02-16 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_auto_20210216_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='emp_id',
        ),
        migrations.AddField(
            model_name='application',
            name='emp_name',
            field=models.CharField(default=None, max_length=50, verbose_name='Approved By'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='user_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name=''),
            preserve_default=False,
        ),
    ]
