# Generated by Django 3.1.7 on 2021-02-20 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210218_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='full_ar_name',
        ),
        migrations.AddField(
            model_name='application',
            name='fh_area',
            field=models.CharField(blank=True, max_length=50, verbose_name='Area'),
        ),
        migrations.AddField(
            model_name='application',
            name='fh_building_no',
            field=models.IntegerField(blank=True, default=0, verbose_name='Building No'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='fh_contact1',
            field=models.CharField(blank=True, max_length=50, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='application',
            name='fh_contact2',
            field=models.CharField(blank=True, max_length=50, verbose_name='Fax'),
        ),
        migrations.AddField(
            model_name='application',
            name='fh_flat_no',
            field=models.IntegerField(blank=True, default=0, verbose_name='Flat No'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='fh_road_no',
            field=models.IntegerField(blank=True, default=0, verbose_name='Road No'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='app_type',
            field=models.CharField(default='Intial Approval', max_length=50, verbose_name='Application Type'),
        ),
        migrations.AlterField(
            model_name='application',
            name='area',
            field=models.CharField(blank=True, max_length=50, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='application',
            name='building_no',
            field=models.IntegerField(blank=True, verbose_name='Building No'),
        ),
        migrations.AlterField(
            model_name='application',
            name='contact1',
            field=models.CharField(blank=True, max_length=50, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='application',
            name='contact2',
            field=models.CharField(blank=True, max_length=50, verbose_name='Fax'),
        ),
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='application',
            name='flat_no',
            field=models.IntegerField(blank=True, verbose_name='Flat No'),
        ),
        migrations.AlterField(
            model_name='application',
            name='full_en_name',
            field=models.CharField(max_length=250, verbose_name='Commercial Eng Name'),
        ),
        migrations.AlterField(
            model_name='application',
            name='license_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='License No'),
        ),
        migrations.AlterField(
            model_name='application',
            name='road_no',
            field=models.IntegerField(blank=True, verbose_name='Road No'),
        ),
    ]
