# Generated by Django 3.1.6 on 2021-02-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210216_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='rent_doc',
            field=models.FileField(upload_to='doc_library', verbose_name='Rental Agreement Doc'),
        ),
    ]
