# Generated by Django 3.1.6 on 2021-02-16 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210216_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='bank_announcement_doc',
        ),
        migrations.RemoveField(
            model_name='application',
            name='employment_office_receipt',
        ),
        migrations.RemoveField(
            model_name='application',
            name='ewa_bill_doc',
        ),
        migrations.RemoveField(
            model_name='application',
            name='license_cancelication_doc',
        ),
        migrations.RemoveField(
            model_name='application',
            name='moh_approval_cert',
        ),
        migrations.RemoveField(
            model_name='application',
            name='mol_approval_cert',
        ),
        migrations.RemoveField(
            model_name='application',
            name='rent_doc',
        ),
    ]
