# Generated by Django 3.1.7 on 2021-02-25 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210225_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='area',
            field=models.CharField(blank=True, max_length=50, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='building_no',
            field=models.IntegerField(blank=True, verbose_name='Building No'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='contact1',
            field=models.CharField(blank=True, max_length=50, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='contact2',
            field=models.CharField(blank=True, max_length=50, verbose_name='Mobile'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='flat_no',
            field=models.IntegerField(blank=True, verbose_name='Flat No'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='road_no',
            field=models.IntegerField(blank=True, verbose_name='Road No'),
        ),
    ]
