# Generated by Django 3.1.6 on 2021-02-16 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210216_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='emp_approval_date',
        ),
        migrations.RemoveField(
            model_name='application',
            name='emp_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='application',
            name='signature_date',
        ),
    ]
