# Generated by Django 3.1.7 on 2021-02-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210225_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='area',
            field=models.CharField(blank=True, max_length=50, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='building_no',
            field=models.IntegerField(default=0, verbose_name='Building No'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='contact1',
            field=models.CharField(blank=True, max_length=50, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='contact2',
            field=models.CharField(blank=True, max_length=50, verbose_name='Fax'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='cr',
            field=models.CharField(blank=True, max_length=50, verbose_name='CR No'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='flat_no',
            field=models.IntegerField(default=0, verbose_name='Flat No'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='full_ar_name',
            field=models.CharField(blank=True, max_length=250, verbose_name='Commercial Arb Name'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='full_en_name',
            field=models.CharField(blank=True, max_length=250, verbose_name='Commercial Eng Name'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='license_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='License No'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='road_no',
            field=models.IntegerField(default=0, verbose_name='Road No'),
        ),
    ]
