# Generated by Django 3.1.7 on 2021-02-26 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210226_1836'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={},
        ),
        migrations.RemoveField(
            model_name='organization',
            name='full_ar_name',
        ),
    ]
