# Generated by Django 3.1.6 on 2021-02-16 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210216_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='app_status',
            field=models.CharField(default='draft', max_length=50, verbose_name='Status'),
        ),
    ]
