# Generated by Django 3.1.6 on 2021-02-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210216_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='nationality',
            field=models.CharField(choices=[('none', 'Select your nationality'), ('bahraini', 'Bahraini'), ('non_bahraini', 'None Bahraini')], default='none', max_length=50, verbose_name='Nationality'),
        ),
    ]
