# Generated by Django 3.1.6 on 2021-02-17 21:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_applicant_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='passport_expiry_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Passport Expire Date'),
            preserve_default=False,
        ),
    ]
