# Generated by Django 3.1.7 on 2021-02-26 20:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210226_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='app_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Application Date'),
        ),
    ]
