# Generated by Django 3.1.6 on 2021-02-17 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_applicant_passport_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='has_application',
            field=models.BooleanField(default=False, verbose_name='Has Applicatino on process'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='is_10000_exist',
            field=models.BooleanField(default=False, verbose_name='Is 10000 BD exist in Applicant Bank Statement'),
        ),
        migrations.AlterField(
            model_name='application',
            name='app_type',
            field=models.CharField(choices=[('new', 'New'), ('renew', 'Renew'), ('modify', 'Modify'), ('license_cancel', 'License Cancelation')], max_length=50, verbose_name='Application Type'),
        ),
    ]
