# Generated by Django 3.1.7 on 2021-02-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20210226_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='app_no',
            field=models.CharField(default='Draft Application', max_length=50, verbose_name='Application No'),
        ),
    ]
