# Generated by Django 3.1.7 on 2021-02-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210226_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='app_type',
            field=models.CharField(default='Initial Approval', max_length=50, verbose_name='Application Type'),
        ),
    ]
