# Generated by Django 3.1.7 on 2021-02-26 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210226_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='building_no',
            field=models.IntegerField(default=0, verbose_name='Building No'),
        ),
        migrations.AlterField(
            model_name='application',
            name='flat_no',
            field=models.IntegerField(default=0, verbose_name='Flat No'),
        ),
        migrations.AlterField(
            model_name='application',
            name='road_no',
            field=models.IntegerField(default=0, verbose_name='Road No'),
        ),
    ]
