# Generated by Django 3.1.7 on 2021-02-26 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0016_auto_20210226_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='cert1_doc',
        ),
        migrations.RemoveField(
            model_name='application',
            name='cert2_doc',
        ),
        migrations.RemoveField(
            model_name='application',
            name='cert3_doc',
        ),
        migrations.RemoveField(
            model_name='application',
            name='cr_ewa_bill_doc',
        ),
        migrations.RemoveField(
            model_name='application',
            name='cr_rent_doc',
        ),
        migrations.RemoveField(
            model_name='application',
            name='employment_office_receipt',
        ),
        migrations.RemoveField(
            model_name='application',
            name='fh_ewa_bill_doc',
        ),
        migrations.RemoveField(
            model_name='application',
            name='fh_rent_doc',
        ),
        migrations.AlterField(
            model_name='application',
            name='applicant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.applicant', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='application',
            name='financial_guarantee',
            field=models.CharField(blank=True, choices=[('manager_cheque', 'Manager Cheque'), ('bank_guarantee', 'Bank Guarantee')], max_length=50, verbose_name='Financial Guarantee'),
        ),
        migrations.AlterField(
            model_name='application',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=''),
        ),
    ]
