# Generated by Django 3.1.7 on 2021-02-28 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20210228_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='bank_statement_doc',
        ),
        migrations.RemoveField(
            model_name='application',
            name='cert1_doc',
        ),
        migrations.RemoveField(
            model_name='application',
            name='cert2_doc',
        ),
        migrations.RemoveField(
            model_name='application',
            name='cert3_doc',
        ),
        migrations.RemoveField(
            model_name='application',
            name='cr_doc',
        ),
        migrations.RemoveField(
            model_name='application',
            name='cr_ewa_bill_doc',
        ),
        migrations.RemoveField(
            model_name='application',
            name='cr_rent_doc',
        ),
        migrations.RemoveField(
            model_name='application',
            name='dreq',
        ),
        migrations.RemoveField(
            model_name='application',
            name='employment_office_receipt',
        ),
        migrations.RemoveField(
            model_name='application',
            name='fh_ewa_bill_doc',
        ),
        migrations.RemoveField(
            model_name='application',
            name='fh_rent_doc',
        ),
        migrations.RemoveField(
            model_name='application',
            name='lmra_agreement',
        ),
        migrations.RemoveField(
            model_name='application',
            name='qnreq',
        ),
        migrations.RemoveField(
            model_name='application',
            name='qsreq',
        ),
    ]
