# Generated by Django 3.1.7 on 2021-02-28 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20210228_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='dreq',
            field=models.FloatField(default=0, verbose_name='Assessments of the level of adequacy of information'),
        ),
        migrations.AddField(
            model_name='application',
            name='qnreq',
            field=models.IntegerField(default=0, verbose_name='Organizational Required Documents No'),
        ),
        migrations.AddField(
            model_name='application',
            name='qsreq',
            field=models.IntegerField(default=0, verbose_name='Uploaded Documents No'),
        ),
    ]
