# Generated by Django 3.1.7 on 2021-02-28 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20210228_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='bank_statement_doc',
            field=models.FileField(blank=True, null=True, upload_to='doc_library', verbose_name='Bank Statement Doc'),
        ),
        migrations.AddField(
            model_name='application',
            name='cert1_doc',
            field=models.FileField(blank=True, null=True, upload_to='doc_library', verbose_name='MOIS Cert'),
        ),
        migrations.AddField(
            model_name='application',
            name='cert2_doc',
            field=models.FileField(blank=True, null=True, upload_to='doc_library', verbose_name='MOH Cert'),
        ),
        migrations.AddField(
            model_name='application',
            name='cert3_doc',
            field=models.FileField(blank=True, null=True, upload_to='doc_library', verbose_name='MOL Cert'),
        ),
        migrations.AddField(
            model_name='application',
            name='cr_doc',
            field=models.FileField(blank=True, null=True, upload_to='doc_library', verbose_name='CR Doc'),
        ),
        migrations.AddField(
            model_name='application',
            name='cr_ewa_bill_doc',
            field=models.FileField(blank=True, null=True, upload_to='doc_library', verbose_name='CR EWA Bill Doc'),
        ),
        migrations.AddField(
            model_name='application',
            name='cr_rent_doc',
            field=models.FileField(blank=True, null=True, upload_to='doc_library', verbose_name='CR Rental Agreement Doc'),
        ),
        migrations.AddField(
            model_name='application',
            name='employment_office_receipt',
            field=models.FileField(blank=True, null=True, upload_to='doc_library', verbose_name='Employment Office Receipt'),
        ),
        migrations.AddField(
            model_name='application',
            name='fh_ewa_bill_doc',
            field=models.FileField(blank=True, null=True, upload_to='doc_library', verbose_name='Temp FH EWA Bill Doc'),
        ),
        migrations.AddField(
            model_name='application',
            name='fh_rent_doc',
            field=models.FileField(blank=True, null=True, upload_to='doc_library', verbose_name='Temp FH Rental Agreement Doc'),
        ),
        migrations.AddField(
            model_name='application',
            name='lmra_agreement',
            field=models.FileField(blank=True, null=True, upload_to='doc_library', verbose_name='LMRA Agreement'),
        ),
    ]
