# Generated by Django 3.1.7 on 2021-02-28 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20210228_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='drec',
            field=models.FloatField(default=0, verbose_name='Adequacy of Recommendations Level'),
        ),
        migrations.AddField(
            model_name='application',
            name='qnrec',
            field=models.IntegerField(default=0, verbose_name='All Recommendations'),
        ),
        migrations.AddField(
            model_name='application',
            name='qsrec',
            field=models.IntegerField(default=0, verbose_name='Satisfying Recommendations'),
        ),
        migrations.AlterField(
            model_name='application',
            name='dreq',
            field=models.FloatField(default=0, verbose_name='Adequacy of Requirements Level'),
        ),
        migrations.AlterField(
            model_name='application',
            name='qnreq',
            field=models.IntegerField(default=0, verbose_name='Org Required Documents'),
        ),
        migrations.AlterField(
            model_name='application',
            name='qsreq',
            field=models.IntegerField(default=0, verbose_name='Uploaded Documents'),
        ),
    ]
