# Generated by Django 3.1.7 on 2021-02-28 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20210228_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='qnrec',
            field=models.IntegerField(default=1, verbose_name='All Recommendations'),
        ),
        migrations.AlterField(
            model_name='application',
            name='qnreq',
            field=models.IntegerField(default=1, verbose_name='Org Required Documents'),
        ),
    ]
