# Generated by Django 3.1.7 on 2021-03-05 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20210305_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='app_status_index',
            field=models.IntegerField(default=0, verbose_name='Status No'),
        ),
    ]
