# Generated by Django 3.1.7 on 2021-03-05 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20210305_0112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='intial_approval',
            new_name='approval',
        ),
    ]
