# Generated by Django 3.1.7 on 2021-03-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20210306_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='app_type',
            field=models.CharField(choices=[('initial', 'Initial Approval'), ('final', 'Final Approval'), ('renew', 'Renewal License'), ('cancel', 'Cancel License')], max_length=50, verbose_name='Application Type'),
        ),
    ]
